import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from './components/Header'
import Image from 'next/image'
import githubBackgroundImage from '../../public/github-background-image.webp';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='fixed -z-10 w-screen h-screen blur-[15px]'>
          <Image
            src={githubBackgroundImage}
            alt="Github background image"
            layout='fill'
            objectFit='cover'
            priority
          />
        </div>
        <Header />
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  )
}
